version: '3'
services:
  db:
    image: mariadb
    container_name: petclinic_db
    restart: always
    networks:
      - backend
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic_db
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
    ports:
      - 7000:3306

networks:
  backend:
